extends Label

var titles = [
	"I Tried [Viral TikTok Trend] So You Don’t Have To",
"What Happens If You Do This Every Day for 30 Days?",
"You Won’t Believe What Just Happened!",
"This Trick Changed My Life in 10 Seconds",
"I Copied a Celebrity’s Routine for a Day",
"Reacting to the Internet’s Craziest Fails",
"You’ve Been Doing This WRONG Your Whole Life",
"TikTok Made Me Buy This… Worth It?",
"I Let AI Control My Life for 24 Hours",
"5-Minute Hacks That Actually Work!?",
"30-Day Transformation – Before & After",
"I Ate Only [Food Type] for a Week",
"No Phone for 24 Hours – Can You Do It?",
"I Tried Waking Up at 5AM for a Week",
"100 Push-Ups a Day for 7 Days",
"Spending $0 for 24 Hours Challenge",
"1 Hour vs 1 Week Results – SHOCKING",
"I Tried Every [Product Type] So You Don’t Have To",
"DIY vs Pro – Who Did It Better?",
"Can You Pass This Impossible Challenge?",
"10 Life Hacks You Wish You Knew Sooner",
"How to Save Time Without Trying",
"Do THIS Every Morning – Life Will Change",
"Genius Amazon Finds You Didn't Know You Needed",
"Easy Habits That Changed My Life",
"5-Minute Crafts That Actually Help",
"How I Organize My Life (Simple System)",
"Productivity Hacks for Lazy People",
"Smart Gadgets You’ll Wish You Bought Sooner",
"Things I Wish I Knew Sooner in Life",
"Reacting to My Old Videos (CRINGE)",
"Kids Today Will NEVER Understand This",
"Top 5 Funniest Internet Moments This Week",
"Reacting to Weird Food Combinations",
"Try Not to Laugh – Challenge Accepted",
"Internet Reacts to [Current Event or Trend]",
"First Time Watching [Popular Show or Movie]",
"People Are Really Doing THIS in Public?!",
"Ranking the Worst [Type of Product] Ever Made",
"Watching This Gave Me Secondhand Embarrassment",
"Morning Routine That Changed Everything",
"Stop Wasting Time – Watch This",
"How I Got My Life Together in 30 Days",
"Why You’re Not Seeing Results (and How to Fix It)",
"I Quit Social Media for a Week – Here’s What Happened",
"What Successful People Do Every Day",
"Best Advice I Ever Got (And Still Use)",
"Daily Habits That Made Me Happier",
"The Truth About Being “Productive”",
"Reset Your Life in 3 Simple Steps",
"What’s Inside a [Mysterious or Weird Object]?",
"I Spent $1 vs $1,000 on [Same Thing]",
"The Most Satisfying Video You’ll Watch Today",
"Can You Spot What’s Wrong With This?",
"This One Trick Is Breaking the Internet",
"Would You Try This? (Be Honest)",
"I Made This Using Only [Unusual Item]",
"5 Things You Didn't Know You Needed",
"This Should Be Illegal to Watch",
"The Internet Wasn’t Ready for This"
]

func _ready() -> void:
	var random_title = randi_range(0, len(titles) - 1)
	$".".text = titles[random_title]
